spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: never
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /**

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

server:
  port: ${PORT:8080}